### ISSUE TITLE
Multiple CI jobs broken on `master`

### ISSUE THREAD

**Issue by sloede** [JuliaParallel/MPI.jl#749]
It seems like multiple CI jobs are broken, e.g.,
- [x] [test-openmpi-jll (ubuntu-latest, 1.6, x86)](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217861774#logs) fails with [`ERROR: LoadError: UndefVarError: libhsa_runtime64 not defined`](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217861774#step:6:201) (upstream bug in AMDGPU.jl 0.2 with Julia v1.6, but AMDGPU v0.3 requires Julia v1.7).  It doesn't seem to occur anymore.
- [x] [test-mpitrampoline-intel-linux (1.6, 2.10.3)](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217866209#logs) fails with a [segfault in some multithreaded part](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217866209#step:12:378) (#725).  This job doesn't exist anymore with #788
- [X] [test-spack-mvapich (1)](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217866754#logs) fails with yet [another segfault](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217866754#step:11:437) (upstream bug in mvapich: #684, fixed by https://github.com/spack/spack/pull/39058)
- [ ] [test-mpitrampoline-jll (ubuntu-latest, mpitrampoline, 1.6, x64)](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217867494#logs) has some problems with [error testing](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217867494#step:7:371)
- [X] Testing on Windows is [failing](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864100) [in](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864384) [multiple](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864666) [places](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864992) (#555).  Test skipped in #791

Any idea what's going on here?

**Comment by sloede** [comment]
Ah, sorry, I should've checked more carefully - it seems like these tests have been broken for a while now, so nothing to get alarmed about. Still, at least some of those errors seem legit (e.g., the first one complaining about a missing symbol)

**Comment by luraess** [comment]
Yeah, seems most of the AMDGPU CI fails but still tests status shows success.

**Comment by giordano** [comment]
> test-openmpi-jll (ubuntu-latest, 1.6, x86) fails with ERROR: LoadError: UndefVarError: libhsa_runtime64 not defined

That's a crash in building AMDGPU.jl

> test-mpitrampoline-intel-linux (1.6, 2.10.3) fails with a segfault in some multithreaded part 

That's #725.

> test-spack-mvapich (1) fails with yet another segfault

I think that's a bug in MVAPICH which may have been fixed in a later version.

> Testing on Windows is [failing](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864100) [in](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864384) [multiple](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864666) [places](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864992)

#555

**Comment by giordano** [comment]
> That's a crash in building AMDGPU.jl

More specifically, the problem is that an old version of AMDGPU.jl (0.2.17) is picked up, despite
https://github.com/JuliaParallel/MPI.jl/blob/4ba36fa859bad8f1645329320532b7d6d9e9c2da/Project.toml#L22
This should have been fixed in newer versions.

**Comment by sloede** [comment]
> > Testing on Windows is [failing](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864100) [in](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864384) [multiple](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864666) [places](https://github.com/JuliaParallel/MPI.jl/actions/runs/5589496115/jobs/10217864992)
> 
> #555

Are you sure the referenced issue is related to all these failures? Here, I also see premature aborts and errors in `MPI_Waitall`.

**Comment by luraess** [comment]
I'll check more carefully but to me it seems that none of the AMDGPU CI succeeds.

**Comment by giordano** [comment]
> > That's a crash in building AMDGPU.jl
> 
> More specifically, the problem is that an old version of AMDGPU.jl (0.2.17) is picked up, despite
> https://github.com/JuliaParallel/MPI.jl/blob/4ba36fa859bad8f1645329320532b7d6d9e9c2da/Project.toml#L22
> This should have been fixed in newer versions.

AMDGPU.jl 0.3 isn't compatible with Julia v1.6.  I don't see how we can possibly make it work.  We should either drop support for Julia v1.6 or not use AMDGPU at all.

**Comment by sloede** [comment]
> AMDGPU.jl 0.3 isn't compatible with Julia v1.6. I don't see how we can possibly make it work. We should either drop support for Julia v1.6 or not use AMDGPU at all.

Call me naive, but I don't see how anyone still uses MPI.jl + Julia v1.6 for productive workloads. For the sake of returning maintenance efforts, I'd thus vote for dropping v1.6 support.

If this is not possible/desirable, then disable AMDGPU support for Julia v1.6 by adding a corresponding statement to the docs and removing the corresponding test matrix entries.

**Comment by luraess** [comment]
> If this is not possible/desirable, then disable AMDGPU support for Julia v1.6 by adding a corresponding statement to the docs and removing the corresponding test matrix entries.

I'd say that AMDGPU Ext + MPI should be bound to Julia 1.9 & AMDGPU 0.5 as explained in #753

**Comment by giordano** [comment]
AMDGPU is ***always*** a test dependency: https://github.com/JuliaParallel/MPI.jl/blob/abebf657c82149ec52b93a293a36a2fa99de3cf9/test/Project.toml#L2

**Comment by giordano** [comment]
I think we have now cleared most of if not all the persistent failures by either addressing them or skipping consistently failing tests, which are already tracked by specific issues.  If there are other relevant issues it'd be good to open dedicated issues, but I'm going to close this ticket, as CI should now be in a much better shape.
